services:
  cockroachdb:
    image: cockroachdb/cockroach:v25.3.3
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8082:8082"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    environment:
      - COCKROACH_CHANNEL=testing

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    depends_on:
      - cockroachdb
    environment:
      - DB_HOST=cockroachdb
      - DB_PORT=26257
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=singlespark
      - DB_SSLMODE=disable
      - EXTERNAL_API_URL=https://api.karenai.click/swechallenge/list
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
    links:
      - cockroachdb

volumes:
  cockroach-data:
